/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : LCD_Hello.c
*  Description  : Main Program
*  Creation Date: 2025-10-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/

#include "r_smc_entry.h"

int main(void);

// UART, I2C
volatile uint8_t _i2c_send_end; // 送信完了フラグ
volatile uint8_t _uart_end; 
#include "OreLCD.c" // _i2c_send_end と _uart_end は必要

#define DEBUG 1 //0: しない, 1: 軽く, 2: ガチ
#define USE_LCD 0 // 0: 未使用, 1:使う
// Gemini によると、最近のコンパイラは優秀なので static const でメモリを消費することは無い
// と言ってる。試しに #define ではなく static const で書いてみる。
// 可読性が良い気がする。
// それから static は、この .c でのみ有効という意味

static const float vref = 2.49; //ADC参照電圧
static const uint16_t pwm_count = 1000;
// 実際には 0-999 で一周期。RL78/G24 は 1000 を入れれば 100% になる。はず。

static const float duty_const = 81.851064; 
static const float tan_duty = -26.930792;
// D = 81.851064  -26.930792 Vb

static const uint8_t sub_count_max = 64;
// max712 の 1 サイクル 84 秒の間に行う子サイクルに相当

static const uint8_t main_count_max = 132*60/84;
// max712 は 132分でタイムオーバー。

static const uint16_t sub_wait_ms = 84000/64 ;
// max712 の 1サイクル[ms] に 2^sub_count_max 回、子サイクルを回すので、そのウェイト

static float rref = 0.1; //電圧測定抵抗 
static float sma_alfa = 1.0/64.0 ;//SMA移動平均の係数

static float current_target_upper = 1.02; //電流目標上限
static float current_target_lower = 0.98; //電流目標上限
// dI/dDuty[‰]=-0.018A。1A ターゲットなら、おおよそ 2%

int main(void)
{
  float vbat; //電池電圧
  float vbat_sma; //電池電圧 SMA 移動平均
  float vbat_sma_max; // SMA最大値
  int duty; //PWM Duty。計算の都合上 int にしておく
  
  uint8_t sub_count = 1;
  //max712 での 1サイクル内でのカウント
  //便宜上 1から始める
  uint8_t main_count = 1;

  float vr; //抵抗電圧
  float current; //電流

  uint8_t flag_max=0; 
  //最大電圧更新フラグ. 1 で更新

  int duty_hosei=0; //Duty の補正オフセット量

  EI();

  // LED 点灯
  // プルアップなので 0 で点灯
  P2_bit.no2 = 0;

  // PWM を開始。コンフィグレータで 1000‰に指定してある。
  R_Config_TAU0_0_Start()  ;

  #if DEBUG >= 1
  R_Config_UART1_Start();
  // OreUART1_Send_ASCII('S'); // OK
  #endif 

  #if USE_LCD == 1
  OreLCDBegin();    
  #endif 

  #if DEBUG >= 1
  //OreUART1_Send_ASCII('L'); // NG
  //OreUART1_Send_CRLF();
  // SDA と SCL を逆にしてしまう大失敗。--> 直した
  // なぜかここに戻ってきてしまう。
  #endif 

  // ADC 空打ち
  // なんか起動直後の 1回目は変な値を取る気がする。
  // コンフィグレータ設定ピンは ANI30
  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();
  // ANI1 に切り替えて空打ち
  R_Config_ADC_Set_ADChannel (ADCHANNEL1);
  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();
  // ANI30 に戻す
  R_Config_ADC_Set_ADChannel (ADCHANNEL30);

  // ここからが本番
  // ADC の測定
  // 今 ANI30, 電池になってる
  R_Config_ADC_Start();
  while(ADCS==1){};
  R_Config_ADC_Stop();
  vbat = vref * ( (float)ADCR0+0.5 )/4096.0;
  // 回してる最中なら ANI1 に切り替えて抵抗の電圧を測定するが 1回目なので何もしない。
  
  // 最初の計測値で SMA 電圧を埋めておく。一回目だけ。
  vbat_sma = vbat;
  vbat_sma_max = vbat_sma;

  // 目標Duty の決定
  duty = (int)( (duty_const + tan_duty * vbat)/100.0 * (float)(pwm_count) ) ;
  if (duty > pwm_count){ 
    duty = pwm_count;
  } else if (duty < 0){
    duty = 0;
  }
  TDR02=(uint16_t)duty;

  // 電池電圧、電流、Duty補正をUART に出すことにしておこう。

  // LCD も同様
  #if USE_LCD == 1
  OreLCD_Char(0b01010110); //"V"
  OreLCD_Char(0b00111010); //":"
  OreLCD_Fixed(vbat, 4);
  OreLCD_Locate(1,0); //二行目
  OreLCD_Char(0b01001001); //"I"
  OreLCD_Char(0b00111010); //":"
  #endif 

  #if DEBUG >= 1
  // ここは表示される。
  OreUART1_Send_Float(vbat_sma, 8);
  OreUART1_Send_ASCII(',');
  OreUART1_Send_CRLF();
  #endif 

  sub_count=sub_count+1; 

  R_BSP_SoftwareDelay(sub_wait_ms, BSP_DELAY_MILLISECS);

  // これで子サイクルの 1回目が終わった。

  // メインサイクル
  for(; main_count <= main_count_max; main_count++){
    // サブサイクル
    for (; sub_count <= sub_count_max; sub_count++){
      //{{{
      //電池電圧測定
      R_Config_ADC_Set_ADChannel (ADCHANNEL30);
      R_Config_ADC_Start();
      while(ADCS==1){};
      R_Config_ADC_Stop();
      vbat = vref * ( (float)ADCR0+0.5 )/4096.0;
    
      //抵抗電圧測定
      R_Config_ADC_Set_ADChannel (ADCHANNEL1);
      R_Config_ADC_Start();
      while(ADCS==1){};
      R_Config_ADC_Stop();
      vr = vref * ( (float)ADCR0+0.5 )/4096.0;

      //移動平均、最大値チェック
      vbat_sma = vbat * sma_alfa + (1.0-sma_alfa) * vbat_sma;
      
      if (vbat_sma > vbat_sma_max){
        vbat_sma_max = vbat_sma;
        flag_max = 1;
      };

      //電流計算
      current = (vr-vbat)/rref;

      // dI/dDuty = -0.18 A/duty[%] = -0.018A/duty[‰]
      // つまり 0.018A のずれが無ければ、duty を触る価値はない
      // ざっくり 2% で見ておけばいいだろう。
      if (current > current_target_upper){
        duty_hosei=duty_hosei+1;
      } else if (current < current_target_lower ){
        duty_hosei=duty_hosei-1;
      };

      // 今回から duty に補正を掛ける
      duty = (int)( (duty_const + tan_duty * vbat)/100.0 * (float)(pwm_count) ) + duty_hosei ;
      if (duty > pwm_count){ 
        duty = pwm_count;
      } else if (duty < 0){
        duty = 0;
      }

      TDR02=(uint16_t)duty;

      #if DEBUG >= 1
      // 途中で current を出力できなくなる
      OreUART1_Send_Float(vbat_sma, 8);
      OreUART1_Send_ASCII(',');
      OreUART1_Send_Float(vbat_sma_max, 8);
      OreUART1_Send_ASCII(',');
      //OreUART1_Send_Float(vbat, 8);
      //OreUART1_Send_ASCII(',');
      //OreUART1_Send_Float(vr, 8);
      //OreUART1_Send_ASCII(',');
      // なんか知らんけど current止まる. 
      OreUART1_Send_Float(current, 7);
      OreUART1_Send_ASCII(',');
      OreUART1_Send_U16( (uint16_t)duty);
      OreUART1_Send_ASCII(',');
      if( duty_hosei < 0){
        OreUART1_Send_ASCII('-');
        OreUART1_Send_U16( (uint16_t)(-duty_hosei) );
      } else {
        OreUART1_Send_U16( (uint16_t)(-duty_hosei) );
      }
      OreUART1_Send_CRLF();
      #endif 

      // LCD も同様
      #if USE_LCD == 1
      OreLCD_CLS();
      OreLCD_Char(0b01010110); //"V"
      OreLCD_Char(0b00111010); //":"
      OreLCD_Fixed(vbat, 4);
      OreLCD_Locate(1,0); //二行目
      OreLCD_Char(0b01001001); //"I"
      OreLCD_Char(0b00111010); //":"
      OreLCD_Fixed(current, 4);
      #endif
      R_BSP_SoftwareDelay(sub_wait_ms, BSP_DELAY_MILLISECS);
    /* }}} */
    };
    if(flag_max == 0){
      TDR02=pwm_count;
      while(1){
         // LED チカチカ
         P2_bit.no2 = !P2_bit.no2;
         R_BSP_SoftwareDelay(1, BSP_DELAY_SECS);
      };
    }
    sub_count=1;
    flag_max = 0;
  }

  // メインカウント乗り越えたら
  TDR02=pwm_count;
  while(1){
     // LED チカチカ
     P2_bit.no2 = !P2_bit.no2;
     R_BSP_SoftwareDelay(2, BSP_DELAY_SECS);
  };
  return 0;
}

